CREATE DATABASE IF NOT EXISTS `docnexus_cloud`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE `docnexus_cloud`;

CREATE TABLE IF NOT EXISTS `gateway_audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '数据库主键',
  `event_id` VARCHAR(64) NOT NULL COMMENT '事件 ID',
  `request_id` VARCHAR(64) NOT NULL COMMENT '请求 ID',
  `trace_id` VARCHAR(64) NOT NULL COMMENT '全链路追踪 ID',
  `user_id` BIGINT DEFAULT NULL COMMENT '用户 ID',
  `username` VARCHAR(128) DEFAULT NULL COMMENT '用户名',
  `client_ip` VARCHAR(64) NOT NULL COMMENT '客户端 IP',
  `method` VARCHAR(16) NOT NULL COMMENT 'HTTP 方法',
  `path` VARCHAR(512) NOT NULL COMMENT '请求路径',
  `route_id` VARCHAR(128) DEFAULT NULL COMMENT 'Gateway 路由 ID',
  `target_service` VARCHAR(128) DEFAULT NULL COMMENT '目标服务',
  `request_kind` VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT 'USER_OPERATION / AUTO_QUERY / SYSTEM_POLLING / AUTH / UNKNOWN',
  `status_code` INT DEFAULT NULL COMMENT '响应状态码',
  `user_agent` VARCHAR(512) DEFAULT NULL COMMENT 'User-Agent',
  `error_message` VARCHAR(1024) DEFAULT NULL COMMENT '错误信息',
  `occurred_at` DATETIME NOT NULL COMMENT '请求进入 Gateway 的时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '落库时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_gateway_audit_event_id` (`event_id`),
  KEY `idx_gateway_audit_trace_id` (`trace_id`),
  KEY `idx_gateway_audit_request_id` (`request_id`),
  KEY `idx_gateway_audit_user_time` (`user_id`, `occurred_at` DESC),
  KEY `idx_gateway_audit_kind_time` (`request_kind`, `occurred_at` DESC),
  KEY `idx_gateway_audit_status_time` (`status_code`, `occurred_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='网关请求审计日志表';

CREATE TABLE IF NOT EXISTS `security_alert_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '数据库主键',
  `event_id` VARCHAR(64) NOT NULL COMMENT '事件 ID',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT '请求 ID',
  `trace_id` VARCHAR(64) DEFAULT NULL COMMENT '全链路追踪 ID',
  `alert_type` VARCHAR(64) NOT NULL COMMENT '告警类型',
  `alert_level` VARCHAR(32) NOT NULL DEFAULT 'WARN' COMMENT '告警级别',
  `user_id` BIGINT DEFAULT NULL COMMENT '用户 ID',
  `client_ip` VARCHAR(64) NOT NULL COMMENT '客户端 IP',
  `method` VARCHAR(16) DEFAULT NULL COMMENT 'HTTP 方法',
  `path` VARCHAR(512) DEFAULT NULL COMMENT '请求路径',
  `message` VARCHAR(1024) NOT NULL COMMENT '告警说明',
  `detail_json` TEXT COMMENT '脱敏扩展详情',
  `handled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否处理',
  `handled_at` DATETIME DEFAULT NULL COMMENT '处理时间',
  `occurred_at` DATETIME NOT NULL COMMENT '发生时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '落库时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_security_alert_event_id` (`event_id`),
  KEY `idx_security_alert_trace_id` (`trace_id`),
  KEY `idx_security_alert_type_time` (`alert_type`, `occurred_at` DESC),
  KEY `idx_security_alert_ip_time` (`client_ip`, `occurred_at` DESC),
  KEY `idx_security_alert_user_time` (`user_id`, `occurred_at` DESC),
  KEY `idx_security_alert_handled` (`handled`, `occurred_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全告警日志表';

CREATE TABLE IF NOT EXISTS `mq_consume_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '数据库主键',
  `event_id` VARCHAR(64) NOT NULL COMMENT '事件 ID',
  `trace_id` VARCHAR(64) DEFAULT NULL COMMENT '全链路追踪 ID',
  `topic` VARCHAR(128) NOT NULL COMMENT 'Topic',
  `tag` VARCHAR(128) DEFAULT NULL COMMENT 'Tag',
  `consumer_group` VARCHAR(128) NOT NULL COMMENT '消费者组',
  `business_key` VARCHAR(128) DEFAULT NULL COMMENT '业务幂等键',
  `consume_status` VARCHAR(32) NOT NULL DEFAULT 'PROCESSING' COMMENT 'PROCESSING / SUCCESS / FAILED / DLQ',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `consume_started_at` DATETIME DEFAULT NULL COMMENT '消费开始时间',
  `consume_finished_at` DATETIME DEFAULT NULL COMMENT '消费完成时间',
  `duration_ms` BIGINT DEFAULT NULL COMMENT '消费耗时毫秒',
  `error_message` VARCHAR(1024) DEFAULT NULL COMMENT '失败原因',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mq_consume_event_group` (`event_id`, `consumer_group`),
  KEY `idx_mq_consume_trace_id` (`trace_id`),
  KEY `idx_mq_consume_topic_status` (`topic`, `consume_status`, `consume_started_at` DESC),
  KEY `idx_mq_consume_business_key` (`business_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ 消费幂等与耗时日志表';

CREATE TABLE IF NOT EXISTS `event_outbox` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '数据库主键',
  `event_id` VARCHAR(64) NOT NULL COMMENT '事件 ID',
  `trace_id` VARCHAR(64) DEFAULT NULL COMMENT '全链路追踪 ID',
  `topic` VARCHAR(128) NOT NULL COMMENT 'Topic',
  `tag` VARCHAR(128) NOT NULL COMMENT 'Tag',
  `business_key` VARCHAR(128) NOT NULL COMMENT '业务主键',
  `payload_json` TEXT NOT NULL COMMENT '事件内容 JSON',
  `event_status` VARCHAR(32) NOT NULL DEFAULT 'NEW' COMMENT 'NEW / SENDING / SENT / FAILED / DEAD',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `next_retry_at` DATETIME DEFAULT NULL COMMENT '下次重试时间',
  `last_sent_at` DATETIME DEFAULT NULL COMMENT '最近发送时间',
  `error_message` VARCHAR(1024) DEFAULT NULL COMMENT '失败原因',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_outbox_event_id` (`event_id`),
  KEY `idx_event_outbox_trace_id` (`trace_id`),
  KEY `idx_event_outbox_status_retry` (`event_status`, `next_retry_at`),
  KEY `idx_event_outbox_business_key` (`business_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务事件 Outbox 表';

CREATE TABLE IF NOT EXISTS `business_operation_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '数据库主键',
  `event_id` VARCHAR(64) NOT NULL COMMENT '事件 ID',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT '请求 ID',
  `trace_id` VARCHAR(64) DEFAULT NULL COMMENT '全链路追踪 ID',
  `user_id` BIGINT DEFAULT NULL COMMENT '用户 ID',
  `username` VARCHAR(128) DEFAULT NULL COMMENT '用户名',
  `source_service` VARCHAR(128) NOT NULL COMMENT '来源服务',
  `module` VARCHAR(64) NOT NULL COMMENT '业务模块',
  `function_name` VARCHAR(128) NOT NULL COMMENT '业务功能',
  `operation_type` VARCHAR(32) NOT NULL COMMENT '操作类型',
  `operation_name` VARCHAR(128) NOT NULL COMMENT '操作名称',
  `trigger_type` VARCHAR(32) NOT NULL COMMENT 'USER_ACTION / AUTO_QUERY / MQ_CONSUME / SYSTEM_TASK / INTERNAL_CALL',
  `operation_source` VARCHAR(32) NOT NULL COMMENT 'FRONTEND / GATEWAY / MQ / SCHEDULER / SERVICE_INTERNAL',
  `user_visible` TINYINT NOT NULL DEFAULT 0 COMMENT '是否允许普通用户前端展示',
  `business_key` VARCHAR(128) DEFAULT NULL COMMENT '业务键',
  `success` TINYINT NOT NULL COMMENT '是否成功',
  `alert_message` VARCHAR(1024) DEFAULT NULL COMMENT '失败或告警说明',
  `request_headers_json` TEXT COMMENT '脱敏请求头 JSON',
  `method` VARCHAR(16) DEFAULT NULL COMMENT 'HTTP 方法',
  `path` VARCHAR(512) DEFAULT NULL COMMENT '请求路径',
  `client_ip` VARCHAR(64) DEFAULT NULL COMMENT '客户端 IP',
  `user_agent` VARCHAR(512) DEFAULT NULL COMMENT 'User-Agent',
  `occurred_at` DATETIME NOT NULL COMMENT '操作开始时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '操作完成时间',
  `duration_ms` BIGINT DEFAULT NULL COMMENT '业务耗时毫秒',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '落库时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_business_operation_event_id` (`event_id`),
  KEY `idx_business_operation_trace_id` (`trace_id`),
  KEY `idx_business_operation_user_visible_time` (`user_id`, `user_visible`, `occurred_at` DESC),
  KEY `idx_business_operation_user_success_time` (`user_id`, `success`, `occurred_at` DESC),
  KEY `idx_business_operation_user_module_time` (`user_id`, `module`, `occurred_at` DESC),
  KEY `idx_business_operation_trigger_time` (`trigger_type`, `occurred_at` DESC),
  KEY `idx_business_operation_business_key` (`business_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='统一业务操作耗时日志表';
